export interface Provincia {
  code: string;
  name: string;
}

export const PROVINCIAS: Provincia[] = [
  { code: 'VI', name: 'Álava/Araba' },
  { code: 'AB', name: 'Albacete' },
  { code: 'A', name: 'Alicante' },
  { code: 'AL', name: 'Almería' },
  { code: 'O', name: 'Asturias' },
  { code: 'AV', name: 'Ávila' },
  { code: 'BA', name: 'Badajoz' },
  { code: 'B', name: 'Barcelona' },
  { code: 'BI', name: 'Bizkaia' },
  { code: 'BU', name: 'Burgos' },
  { code: 'CC', name: 'Cáceres' },
  { code: 'CA', name: 'Cádiz' },
  { code: 'S', name: 'Cantabria' },
  { code: 'CS', name: 'Castellón' },
  { code: 'CR', name: 'Ciudad Real' },
  { code: 'CO', name: 'Córdoba' },
  { code: 'C', name: 'A Coruña' },
  { code: 'CU', name: 'Cuenca' },
  { code: 'SS', name: 'Gipuzkoa' },
  { code: 'GI', name: 'Girona' },
  { code: 'GR', name: 'Granada' },
  { code: 'GU', name: 'Guadalajara' },
  { code: 'H', name: 'Huelva' },
  { code: 'HU', name: 'Huesca' },
  { code: 'PM', name: 'Illes Balears' },
  { code: 'J', name: 'Jaén' },
  { code: 'LE', name: 'León' },
  { code: 'L', name: 'Lleida' },
  { code: 'LU', name: 'Lugo' },
  { code: 'M', name: 'Madrid' },
  { code: 'MA', name: 'Málaga' },
  { code: 'MU', name: 'Murcia' },
  { code: 'NA', name: 'Navarra' },
  { code: 'OU', name: 'Ourense' },
  { code: 'P', name: 'Palencia' },
  { code: 'GC', name: 'Las Palmas' },
  { code: 'PO', name: 'Pontevedra' },
  { code: 'LO', name: 'La Rioja' },
  { code: 'SA', name: 'Salamanca' },
  { code: 'TF', name: 'Santa Cruz de Tenerife' },
  { code: 'SG', name: 'Segovia' },
  { code: 'SE', name: 'Sevilla' },
  { code: 'SO', name: 'Soria' },
  { code: 'T', name: 'Tarragona' },
  { code: 'TE', name: 'Teruel' },
  { code: 'TO', name: 'Toledo' },
  { code: 'V', name: 'Valencia' },
  { code: 'VA', name: 'Valladolid' },
  { code: 'ZA', name: 'Zamora' },
  { code: 'Z', name: 'Zaragoza' },
];

export const CIUDADES_POR_PROVINCIA: Record<string, string[]> = {
  VI: ['Vitoria-Gasteiz', 'Llodio', 'Amurrio', 'Salvatierra/Agurain', 'Oyón-Oion', 'Alegría-Dulantzi'],
  AB: ['Albacete', 'Hellín', 'Villarrobledo', 'Almansa', 'La Roda', 'Caudete', 'Tobarra', 'Casas-Ibáñez'],
  A: ['Alicante', 'Elche', 'Torrevieja', 'Orihuela', 'Benidorm', 'Alcoy', 'Elda', 'San Vicente del Raspeig', 'Dénia', 'Villena', 'Petrer', 'Crevillente'],
  AL: ['Almería', 'El Ejido', 'Roquetas de Mar', 'Níjar', 'Adra', 'Vícar', 'Huércal-Overa', 'Berja', 'Cuevas del Almanzora'],
  O: ['Oviedo', 'Gijón', 'Avilés', 'Siero', 'Langreo', 'Mieres', 'Castrillón', 'San Martín del Rey Aurelio', 'Cangas del Narcea', 'Laviana'],
  AV: ['Ávila', 'Arévalo', 'Las Navas del Marqués', 'Candeleda', 'Arenas de San Pedro', 'El Tiemblo', 'Sotillo de la Adrada'],
  BA: ['Badajoz', 'Mérida', 'Don Benito', 'Almendralejo', 'Villanueva de la Serena', 'Zafra', 'Montijo', 'Olivenza', 'Villafranca de los Barros', 'Jerez de los Caballeros'],
  B: ['Barcelona', 'Hospitalet de Llobregat', 'Badalona', 'Terrassa', 'Sabadell', 'Mataró', 'Santa Coloma de Gramenet', 'Cornellà de Llobregat', 'Sant Boi de Llobregat', 'Rubí', 'Manresa', 'Vilanova i la Geltrú', 'Granollers', 'Vic'],
  BI: ['Bilbao', 'Barakaldo', 'Getxo', 'Portugalete', 'Santurtzi', 'Basauri', 'Leioa', 'Galdakao', 'Durango', 'Erandio', 'Sestao', 'Gernika-Lumo'],
  BU: ['Burgos', 'Miranda de Ebro', 'Aranda de Duero', 'Briviesca', 'Medina de Pomar', 'Lerma', 'Villarcayo'],
  CC: ['Cáceres', 'Plasencia', 'Navalmoral de la Mata', 'Coria', 'Trujillo', 'Miajadas', 'Moraleja', 'Jaraíz de la Vera'],
  CA: ['Cádiz', 'Jerez de la Frontera', 'Algeciras', 'San Fernando', 'El Puerto de Santa María', 'Chiclana de la Frontera', 'Sanlúcar de Barrameda', 'La Línea de la Concepción', 'Puerto Real', 'Rota', 'Arcos de la Frontera'],
  S: ['Santander', 'Torrelavega', 'Castro-Urdiales', 'Camargo', 'Piélagos', 'El Astillero', 'Laredo', 'Santa Cruz de Bezana', 'Los Corrales de Buelna', 'Reinosa'],
  CS: ['Castellón de la Plana', 'Vila-real', 'Burriana', 'Vinaròs', 'Benicarló', "La Vall d'Uixó", 'Onda', 'Almassora', 'Benicàssim', 'Nules'],
  CR: ['Ciudad Real', 'Puertollano', 'Tomelloso', 'Alcázar de San Juan', 'Valdepeñas', 'Manzanares', 'Daimiel', 'La Solana', 'Miguelturra', 'Bolaños de Calatrava'],
  CO: ['Córdoba', 'Lucena', 'Puente Genil', 'Montilla', 'Priego de Córdoba', 'Cabra', 'Baena', 'Palma del Río', 'Peñarroya-Pueblonuevo', 'Pozoblanco'],
  C: ['A Coruña', 'Santiago de Compostela', 'Ferrol', 'Narón', 'Oleiros', 'Arteixo', 'Carballo', 'Culleredo', 'Cambre', 'Ribeira', 'Betanzos'],
  CU: ['Cuenca', 'Tarancón', 'San Clemente', 'Las Pedroñeras', 'Quintanar del Rey', 'Motilla del Palancar'],
  SS: ['Donostia-San Sebastián', 'Irun', 'Errenteria', 'Eibar', 'Zarautz', 'Arrasate/Mondragón', 'Hernani', 'Tolosa', 'Hondarribia', 'Bergara', 'Oñati', 'Azpeitia'],
  GI: ['Girona', 'Figueres', 'Blanes', 'Lloret de Mar', 'Olot', 'Salt', 'Palafrugell', 'Sant Feliu de Guíxols', 'Roses', 'Banyoles'],
  GR: ['Granada', 'Motril', 'Almuñécar', 'Armilla', 'Maracena', 'Loja', 'Baza', 'Guadix', 'Santa Fe', 'Las Gabias', 'Salobreña'],
  GU: ['Guadalajara', 'Azuqueca de Henares', 'Alovera', 'Cabanillas del Campo', 'El Casar', 'Marchamalo', 'Sigüenza', 'Molina de Aragón'],
  H: ['Huelva', 'Lepe', 'Almonte', 'Isla Cristina', 'Moguer', 'Ayamonte', 'Cartaya', 'Bollullos Par del Condado', 'Punta Umbría', 'Valverde del Camino'],
  HU: ['Huesca', 'Monzón', 'Barbastro', 'Jaca', 'Fraga', 'Sabiñánigo', 'Binéfar', 'Sariñena'],
  PM: ['Palma', 'Calvià', 'Manacor', 'Llucmajor', 'Marratxí', 'Inca', 'Ibiza', 'Santa Eulària des Riu', 'Ciutadella de Menorca', 'Maó-Mahón', 'Felanitx', 'Sóller'],
  J: ['Jaén', 'Linares', 'Andújar', 'Úbeda', 'Martos', 'Alcalá la Real', 'Baeza', 'La Carolina', 'Jódar', 'Torredonjimeno'],
  LE: ['León', 'Ponferrada', 'San Andrés del Rabanedo', 'Villaquilambre', 'Astorga', 'La Bañeza', 'Bembibre', 'Villablino', 'Cacabelos'],
  L: ['Lleida', 'Balaguer', 'Tàrrega', 'Mollerussa', "La Seu d'Urgell", 'Cervera', 'Les Borges Blanques', 'Almacelles', 'Solsona'],
  LU: ['Lugo', 'Monforte de Lemos', 'Viveiro', 'Vilalba', 'Sarria', 'Burela', 'Foz', 'Chantada', 'Ribadeo'],
  M: ['Madrid', 'Móstoles', 'Alcalá de Henares', 'Fuenlabrada', 'Leganés', 'Getafe', 'Alcorcón', 'Torrejón de Ardoz', 'Parla', 'Alcobendas', 'Las Rozas de Madrid', 'San Sebastián de los Reyes', 'Pozuelo de Alarcón', 'Coslada', 'Rivas-Vaciamadrid'],
  MA: ['Málaga', 'Marbella', 'Vélez-Málaga', 'Mijas', 'Fuengirola', 'Torremolinos', 'Benalmádena', 'Estepona', 'Rincón de la Victoria', 'Antequera', 'Ronda', 'Nerja'],
  MU: ['Murcia', 'Cartagena', 'Lorca', 'Molina de Segura', 'Alcantarilla', 'Torre-Pacheco', 'Águilas', 'Mazarrón', 'Cieza', 'Yecla', 'Totana', 'Caravaca de la Cruz'],
  NA: ['Pamplona/Iruña', 'Tudela', 'Barañáin', 'Burlada/Burlata', 'Estella-Lizarra', 'Zizur Mayor', 'Tafalla', 'Villava/Atarrabia', 'Ansoáin', 'Berriozar'],
  OU: ['Ourense', 'Verín', 'O Barco de Valdeorras', 'Carballiño', 'Xinzo de Limia', 'Celanova', 'Allariz', 'Ribadavia'],
  P: ['Palencia', 'Aguilar de Campoo', 'Guardo', 'Venta de Baños', 'Dueñas', 'Villamuriel de Cerrato', 'Cervera de Pisuerga'],
  GC: ['Las Palmas de Gran Canaria', 'Telde', 'Santa Lucía de Tirajana', 'Arrecife', 'San Bartolomé de Tirajana', 'Arucas', 'Puerto del Rosario', 'Agüimes', 'Ingenio', 'Gáldar', 'Teguise', 'Mogán'],
  PO: ['Pontevedra', 'Vigo', 'Vilagarcía de Arousa', 'Redondela', 'Cangas', 'Marín', 'Ponteareas', 'Lalín', 'Tui', 'O Grove', 'Moaña', 'Baiona'],
  LO: ['Logroño', 'Calahorra', 'Arnedo', 'Haro', 'Alfaro', 'Lardero', 'Nájera', 'Santo Domingo de la Calzada'],
  SA: ['Salamanca', 'Béjar', 'Ciudad Rodrigo', 'Santa Marta de Tormes', 'Carbajosa de la Sagrada', 'Villares de la Reina', 'Peñaranda de Bracamonte', 'Alba de Tormes'],
  TF: ['Santa Cruz de Tenerife', 'San Cristóbal de La Laguna', 'Arona', 'Adeje', 'La Orotava', 'Granadilla de Abona', 'Los Realejos', 'Puerto de la Cruz', 'Candelaria', 'Güímar', 'Icod de los Vinos', 'Tacoronte'],
  SG: ['Segovia', 'Cuéllar', 'El Espinar', 'San Ildefonso', 'Cantalejo', 'Carbonero el Mayor', 'Nava de la Asunción'],
  SE: ['Sevilla', 'Dos Hermanas', 'Alcalá de Guadaíra', 'Utrera', 'Mairena del Aljarafe', 'Écija', 'Los Palacios y Villafranca', 'Carmona', 'La Rinconada', 'Coria del Río', 'Bormujos', 'Osuna'],
  SO: ['Soria', 'Almazán', 'El Burgo de Osma', 'San Esteban de Gormaz', 'Ólvega', 'Ágreda'],
  T: ['Tarragona', 'Reus', 'Tortosa', 'El Vendrell', 'Cambrils', 'Salou', 'Valls', 'Vila-seca', 'Amposta', 'Calafell'],
  TE: ['Teruel', 'Alcañiz', 'Andorra', 'Calamocha', 'Utrillas', 'Monreal del Campo', 'Cella'],
  TO: ['Toledo', 'Talavera de la Reina', 'Illescas', 'Seseña', 'Sonseca', 'Madridejos', 'Consuegra', 'Quintanar de la Orden', 'Mora', 'Ocaña'],
  V: ['Valencia', 'Torrent', 'Gandía', 'Paterna', 'Sagunto', 'Alzira', 'Mislata', 'Burjassot', 'Ontinyent', 'Manises', 'Xàtiva', 'Sueca', 'Requena', 'Cullera'],
  VA: ['Valladolid', 'Medina del Campo', 'Laguna de Duero', 'Arroyo de la Encomienda', 'Tordesillas', 'Íscar', 'Tudela de Duero', 'Peñafiel', 'Simancas'],
  ZA: ['Zamora', 'Benavente', 'Toro', 'Morales del Vino', 'Villalpando', 'Puebla de Sanabria', 'Fuentesaúco'],
  Z: ['Zaragoza', 'Calatayud', 'Utebo', 'Ejea de los Caballeros', 'Tarazona', 'Caspe', 'Zuera', 'Cuarte de Huerva', 'La Almunia de Doña Godina', 'Alagón', 'Tauste'],
};

export function getAllProvincias(): Provincia[] {
  return PROVINCIAS;
}

export function getCiudadesByProvincia(code: string): string[] {
  return CIUDADES_POR_PROVINCIA[code] ?? [];
}

export function getProvinciaByCode(code: string): Provincia | undefined {
  return PROVINCIAS.find((p) => p.code === code);
}
